# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PDFMerger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 750)
        MainWindow.setMinimumSize(QtCore.QSize(750, 750))
        MainWindow.setMaximumSize(QtCore.QSize(750, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(750, 750))
        self.centralwidget.setMaximumSize(QtCore.QSize(750, 750))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_upload_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_upload_frame.sizePolicy().hasHeightForWidth())
        self.file_upload_frame.setSizePolicy(sizePolicy)
        self.file_upload_frame.setMinimumSize(QtCore.QSize(730, 100))
        self.file_upload_frame.setMaximumSize(QtCore.QSize(710, 100))
        self.file_upload_frame.setStyleSheet("border: 5px solid rgb(0, 43, 91);")
        self.file_upload_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_upload_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_upload_frame.setObjectName("file_upload_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.file_upload_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_file_name = QtWidgets.QLabel(self.file_upload_frame)
        self.lbl_file_name.setMinimumSize(QtCore.QSize(430, 60))
        self.lbl_file_name.setMaximumSize(QtCore.QSize(430, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_file_name.setFont(font)
        self.lbl_file_name.setStyleSheet("border: 2px solid rgb(36, 105, 127);\n"
"border-radius: 15px;")
        self.lbl_file_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_file_name.setWordWrap(True)
        self.lbl_file_name.setObjectName("lbl_file_name")
        self.horizontalLayout.addWidget(self.lbl_file_name)
        self.btn_upload_file = QtWidgets.QPushButton(self.file_upload_frame)
        self.btn_upload_file.setMinimumSize(QtCore.QSize(180, 60))
        self.btn_upload_file.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_upload_file.setFont(font)
        self.btn_upload_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_upload_file.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(36, 105, 127);\n"
"font: 75 12pt;\n"
"border-radius: 30px;\n"
"background-color: rgb(137, 218, 199);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(125, 199, 181);\n"
"}\n"
"")
        self.btn_upload_file.setObjectName("btn_upload_file")
        self.horizontalLayout.addWidget(self.btn_upload_file)
        self.verticalLayout.addWidget(self.file_upload_frame)
        self.merge_frame = QtWidgets.QFrame(self.centralwidget)
        self.merge_frame.setMinimumSize(QtCore.QSize(730, 100))
        self.merge_frame.setMaximumSize(QtCore.QSize(710, 100))
        self.merge_frame.setStyleSheet("border: 5px solid rgb(0, 43, 91);")
        self.merge_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.merge_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.merge_frame.setObjectName("merge_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.merge_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.merge_frame)
        self.label.setMinimumSize(QtCore.QSize(110, 60))
        self.label.setMaximumSize(QtCore.QSize(110, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cmb_page_size = QtWidgets.QComboBox(self.merge_frame)
        self.cmb_page_size.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_page_size.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_page_size.setFont(font)
        self.cmb_page_size.setStyleSheet("border: 2px solid rgb(0, 43, 91);")
        self.cmb_page_size.setObjectName("cmb_page_size")
        self.cmb_page_size.addItem("")
        self.cmb_page_size.addItem("")
        self.cmb_page_size.addItem("")
        self.cmb_page_size.addItem("")
        self.cmb_page_size.addItem("")
        self.cmb_page_size.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_page_size)
        spacerItem = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_merge_file = QtWidgets.QPushButton(self.merge_frame)
        self.btn_merge_file.setMinimumSize(QtCore.QSize(180, 60))
        self.btn_merge_file.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_merge_file.setFont(font)
        self.btn_merge_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_merge_file.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(36, 105, 127);\n"
"font: 75 12pt;\n"
"border-radius: 30px;\n"
"background-color: rgb(137, 218, 199);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(125, 199, 181);\n"
"}\n"
"")
        self.btn_merge_file.setObjectName("btn_merge_file")
        self.horizontalLayout_2.addWidget(self.btn_merge_file)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.merge_frame)
        self.download_frame = QtWidgets.QFrame(self.centralwidget)
        self.download_frame.setMinimumSize(QtCore.QSize(730, 100))
        self.download_frame.setMaximumSize(QtCore.QSize(710, 100))
        self.download_frame.setStyleSheet("border: 5px solid rgb(0, 43, 91);")
        self.download_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.download_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.download_frame.setObjectName("download_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.download_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_download_file = QtWidgets.QPushButton(self.download_frame)
        self.btn_download_file.setEnabled(False)
        self.btn_download_file.setMinimumSize(QtCore.QSize(180, 60))
        self.btn_download_file.setMaximumSize(QtCore.QSize(180, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_download_file.setFont(font)
        self.btn_download_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_download_file.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(36, 105, 127);\n"
"font: 75 12pt;\n"
"border-radius: 30px;\n"
"background-color: rgb(137, 218, 199);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(125, 199, 181);\n"
"}\n"
"")
        self.btn_download_file.setObjectName("btn_download_file")
        self.horizontalLayout_4.addWidget(self.btn_download_file)
        self.verticalLayout.addWidget(self.download_frame)
        self.status_frame = QtWidgets.QFrame(self.centralwidget)
        self.status_frame.setMinimumSize(QtCore.QSize(730, 380))
        self.status_frame.setMaximumSize(QtCore.QSize(730, 380))
        self.status_frame.setStyleSheet("border: 3px solid rgb(0, 43, 91);")
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.status_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_status = QtWidgets.QTextEdit(self.status_frame)
        self.edit_status.setMinimumSize(QtCore.QSize(700, 350))
        self.edit_status.setMaximumSize(QtCore.QSize(730, 380))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.edit_status.setFont(font)
        self.edit_status.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"padding: 10px;")
        self.edit_status.setReadOnly(True)
        self.edit_status.setObjectName("edit_status")
        self.horizontalLayout_3.addWidget(self.edit_status)
        self.verticalLayout.addWidget(self.status_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_file_name.setText(_translate("MainWindow", "PDF name"))
        self.btn_upload_file.setText(_translate("MainWindow", "Upload File"))
        self.label.setText(_translate("MainWindow", "Page Size"))
        self.cmb_page_size.setItemText(0, _translate("MainWindow", "A4"))
        self.cmb_page_size.setItemText(1, _translate("MainWindow", "A3"))
        self.cmb_page_size.setItemText(2, _translate("MainWindow", "30x20"))
        self.cmb_page_size.setItemText(3, _translate("MainWindow", "15x20"))
        self.cmb_page_size.setItemText(4, _translate("MainWindow", "15x10"))
        self.cmb_page_size.setItemText(5, _translate("MainWindow", "Legal"))
        self.btn_merge_file.setText(_translate("MainWindow", "Merge File"))
        self.btn_download_file.setText(_translate("MainWindow", "Download File"))
        self.edit_status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
